### ISSUE TITLE
xensuspend build fail with pyxs package

### ISSUE THREAD

**Issue by xenpm** [lorc/xensuspend#1]
Build xen-troops fail on xensuspend package
From error log, pyxs package fail 
```
| Traceback (most recent call last):
|   File "setup.py", line 44, in <module>
|     url="https://github.com/selectel/pyxs")
...
|   File "/tmp/easy_install-utzat5es/pytest-runner-5.3.0/temp/easy_install-jpugg89h/setuptools_scm-6.0.1/src/setuptools_scm/__init__.py", line 15, in <module>
|   File "/tmp/easy_install-utzat5es/pytest-runner-5.3.0/temp/easy_install-jpugg89h/setuptools_scm-6.0.1/src/setuptools_scm/version.py", line 42
|     trace(f"tag '{tag}' parsed to {result}")
|                                           ^
| SyntaxError: invalid syntax
| ERROR: python3 setup.py build_ext execution failed.
| WARNING: exit code 1 from a shell command.
```
trace(f"tag '{tag}' parsed to {result}") 
Above command fail since it is python3.6+ format, currently our host machine used python3.5.3 
This issue come from package setuptools_scm v6.0.1
Is there any way to fixed package setuptools_scm to a lower version, so we can avoid this issue

**Comment by lorc** [comment]
Hello.

Well, looks like `pyxs` requires/uses more recent setuptools. 

You can try to use lower version of `pyxs` but this can cause some other dependency issues. Try this change to `setup.py`:

```
      description='Xen system suspend coordinator',
      url='https://github.com/xen-troops/xensuspend',
      license='GPLv2',
-     install_requires=["pyxs>=0.3"],
+     install_requires=["pyxs=0.3"],
      scripts=['bin/xensuspend']
    )
```

Or try to install `pyxs` v0.3 manually using pip:

```
$ pip install pyxs=0.3
```

**Comment by xenpm** [comment]
Hi Mr,

Thanks for your support and sorry for late respond
I'm using your package with xen-troops so it took around 6h to actually confirm your advice. 

At the result, the issue is solved, currently there is no other issue related to dependency things. So I would like to apply your solution in my project.

Thank you
